### ISSUE TITLE
安装时提示缺少这个plugin.xml文件

### ISSUE THREAD

**Issue by doudadou** [wangxiaochuan366/cordova_alipay#1]

**Comment by wangxiaochuan366** [comment]
已经提交了  不好意思   忘记吧屏蔽关掉了

**Comment by doudadou** [comment]
感谢，已经安装成功了，但是调用的时候会报这个错误呢
`Error: undefined is not an object (evaluating 'window.alipay.pay')`
还需要引入什么内容么

**Comment by wangxiaochuan366** [comment]
如果你是新手，如果你只是想简单的调用 ， 建议你按照我readme 里面给出的原作者的地址 。    我这个是改装过的安全性更高的插件   必须要有后台支持，签名等重要信息不放在客服端由ajax向后台获取。

**Comment by wangxiaochuan366** [comment]
https://github.com/charleyw/cordova-plugin-alipay    我是在他的基础上优化的，如果有什么不懂的，欢迎骚扰

**Comment by doudadou** [comment]
应该是混淆的hook插件造成的
然后咨询下私有key自动安装的时候也是填写的了，需要删掉么，如果是从后端拿签名的话，谢谢

**Comment by wangxiaochuan366** [comment]
要删除的 ，全部从后端获取，注意签名时候参数的顺序

**Comment by wangxiaochuan366** [comment]
提交一些必要的参数给服务端，然后使用返回的数据
window.alipay.pay(后端获取, function(successResults) {
                if(successResults.resultStatus == 9000){
 }
}

**Comment by doudadou** [comment]
好的，万分感谢，我尝试下

**Comment by wangxiaochuan366** [comment]
建议你先把原作者的先调通，在尝试我这个，不然后面坑不好填

**Comment by doudadou** [comment]
刚试了下可以调出，可以用了，哈哈哈

**Comment by wangxiaochuan366** [comment]
是原版 还是我改过的版本？

**Comment by doudadou** [comment]
暂时跑通了原版的，等后端把校验弄好了，再试下你的这版

**Comment by wangxiaochuan366** [comment]
现在基本上都是RSA 这个不太重要，不管哪种方式都能实现。

**Comment by doudadou** [comment]
Error: undefined is not an object (evaluating 'window.alipay.pay') 用回来，又开始报这个错误了。。奇怪，重新部署个环境还是这样

**Comment by doudadou** [comment]
可以跑通了，感谢 ：）

**Comment by wangxiaochuan366** [comment]
用我改过的版本？昨天你发消息的时候我已经下班了，没看到邮件提醒。

**Comment by doudadou** [comment]
恩呢，就是这个版本

**Comment by wangxiaochuan366** [comment]
好吧  偷偷告诉你，你是第一个用这个版本的人。 别忘记点Star啊。

**Comment by doudadou** [comment]
哈哈，第二个Star的就是在下了

**Comment by wangxiaochuan366** [comment]
请问在哪高就啊

**Comment by doudadou** [comment]
一个创业小团队，你呢

**Comment by wangxiaochuan366** [comment]
我的意思是坐标啊

**Comment by doudadou** [comment]
在北京

**Comment by wangxiaochuan366** [comment]
好吧  我在魔都
